services:
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  jarvis-python:
    image: jako3519/jarvis-python:latest
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./assets:/app/assets
    depends_on:
      - mosquitto

  jarvis-csharp:
    image: jako3519/jarvis-csharp:latest
    restart: unless-stopped
    depends_on:
      - mosquitto

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_90e8e0dad378f011a3a6efeba7772636-if00-port0:/dev/ttyUSB0
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mosquitto

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup